'use strict';

/**
 * report.js — Markdown report generator for OSS Radar
 */

var LEVEL_ICON = { A: 'A', B: 'B', C: 'C', D: 'D' };

/**
 * @param {object} result — from searchProjects or compareRepos
 * @param {string} title
 * @returns {string} markdown report
 */
function generateReport(result, title) {
  var lines = [];
  lines.push('# ' + (title || 'OSS Radar Report'));
  lines.push('');
  lines.push('Generated: ' + new Date().toISOString());
  lines.push('');

  if (result.query) {
    lines.push('Query: `' + result.query + '`');
    lines.push('');
  }

  var items = result.results || [];
  if (items.length === 0) {
    lines.push('No results found.');
    return lines.join('\n');
  }

  lines.push('| Rank | Project | Stars | Forks | Language | Score | Level |');
  lines.push('|------|---------|-------|-------|----------|-------|-------|');

  items.forEach(function (item, i) {
    var name = item.name || 'unknown';
    var stars = item.stars || 0;
    var forks = item.forks || 0;
    var lang = item.language || '-';
    var score = item.score || 0;
    var level = item.level || 'D';

    lines.push('| ' + (i + 1) + ' | ' + name + ' | ' + stars + ' | ' + forks +
      ' | ' + lang + ' | ' + score + ' | ' + level + ' |');
  });

  lines.push('');
  lines.push('## Top Results');

  items.forEach(function (item, i) {
    if (i >= 3) return;
    lines.push('');
    lines.push('### ' + (i + 1) + '. ' + item.name + ' (Score: ' + item.score + ')');
    if (item.description) lines.push(item.description);
    if (item.url) lines.push('Link: ' + item.url);
  });

  lines.push('');
  lines.push('---');
  lines.push('Generated by OSS Radar v1.0 | No clone. No install. API only.');

  return lines.join('\n');
}

module.exports = { generateReport: generateReport };
