"use strict";

/**
 * codex-agent.js - Codex PR Agent
 *
 * 默认 plan-only: 返回执行计划
 * confirm:create-pr: 创建 feature 分支 + Draft PR
 *
 * P7.2.1: AI Runtime RBAC 权限由 agent-dispatcher 在调用前统一检查
 *         允许: patch, tests, draft-pr
 *         拒绝: deploy-production, modify-nginx, modify-env, pm2-restart, git-push-main
 */

const { createBranch, commitFile, createDraftPR, parseRepo } = require("./github-pr-client");
const { sanitizeOutput, securityCheck } = require("../orchestrator/v2/commander-policy");
const { createTask, updateTask } = require("../orchestrator/v2/task-store");

const CONFIRM_KEYWORD = "confirm:create-pr";

/**
 * 检测内容是否包含 create-pr 确认指令
 */
function isCreatePRRequest(content) {
  if (!content) return false;
  return content.toLowerCase().indexOf(CONFIRM_KEYWORD.toLowerCase()) !== -1;
}

/**
 * 从内容中剥离 confirm 指令，返回干净的 task 内容
 */
function stripConfirmKeyword(content) {
  if (!content) return "";
  return content
    .replace(new RegExp(CONFIRM_KEYWORD, "gi"), "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * 生成安全的分支名 slug
 */
function generateBranchSlug(content, maxLen) {
  maxLen = maxLen || 40;
  return content
    .replace(/[^a-zA-Z0-9\u4e00-\u9fff_-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase()
    .slice(0, maxLen);
}

/**
 * 生成 plan 文件内容 (Markdown)
 */
function generatePlanContent(content) {
  var now = new Date().toISOString();
  return [
    "# Codex Plan",
    "",
    "> 生成时间: " + now,
    "> 来源: WeCom /任务 codex confirm:create-pr",
    "",
    "## 任务内容",
    "",
    content,
    "",
    "## 执行计划",
    "",
    "1. 分析需求上下文和代码库结构",
    "2. 定位需要修改的模块和文件",
    "3. 设计变更方案",
    "4. 编写代码 patch",
    "5. 本地测试验证",
    "6. 提交 PR 并请求 Review",
    "",
    "## 安全约束",
    "",
    "- 禁止自动 merge",
    "- 禁止自动 deploy",
    "- 需通过 Code Review 才能合并",
    "",
    "---",
    "",
    "*此文件由 Codex PR Agent 自动生成*"
  ].join("\n");
}

/**
 * 生成 PR body
 */
function generatePRBody(content, branch, taskId) {
  return [
    "## Codex PR Agent",
    "",
    "**任务**: " + content,
    "**Task ID**: " + taskId,
    "**分支**: " + branch,
    "",
    "### 说明",
    "",
    "此 PR 由 WeCom `/任务 codex confirm:create-pr` 指令自动创建。",
    "",
    "### 安全策略",
    "",
    "- [ ] 禁止自动 merge",
    "- [ ] 禁止自动 deploy",
    "- [ ] 需 Code Review 后手动合并",
    "",
    "---",
    "*Generated by Codex PR Agent v1*"
  ].join("\n");
}

/**
 * Mock plan-only 响应 (与 agent-dispatcher 中原 AGENT_RESPONSES.codex 一致)
 */
function mockPlanOnly(content) {
  return {
    plan: [
      "[Codex] 分析任务: \"" + content + "\"",
      "[Codex] 步骤1: 理解需求上下文",
      "[Codex] 步骤2: 检索相关代码库",
      "[Codex] 步骤3: 生成实现方案",
      "[Codex] 步骤4: 验证方案可行性",
      "[Codex] plan-only 模式: 仅提供计划，不执行代码变更"
    ].join("\n"),
    estimatedTime: "~5 分钟"
  };
}

/**
 * Codex Agent 主执行函数
 *
 * @param {Object} params
 * @param {string} params.content - 任务内容
 * @param {string} params.taskId - 任务 ID
 * @param {string} params.command - 触发命令
 * @returns {Object} dispatch 格式的响应
 */
async function execute(params) {
  var content = params.content || "";
  var taskId = params.taskId;
  var command = params.command || "/任务";

  // 安全检查
  var security = securityCheck({ agent: "codex", content: content, command: command });
  if (!security.passed) {
    return {
      success: false,
      error: "安全检查失败:\n" + security.violations.map(function(v) { return "- " + v; }).join("\n"),
      task_id: taskId,
      result: null
    };
  }

  // 默认 plan-only
  if (!isCreatePRRequest(content)) {
    var mockRes = mockPlanOnly(content);
    var sanitizedPlan = sanitizeOutput(mockRes.plan);

    var result = {
      task_id: taskId,
      agent: "codex",
      plan: sanitizedPlan,
      estimated_time: mockRes.estimatedTime,
      mode: "plan-only",
      security_warnings: security.warnings,
      timestamp: new Date().toISOString()
    };

    updateTask(taskId, {
      status: "completed",
      result: JSON.stringify(result)
    });

    return {
      success: true,
      task_id: taskId,
      result: result
    };
  }

  // === confirm:create-pr 模式 ===
  var cleanContent = stripConfirmKeyword(content);

  // 更新任务状态
  updateTask(taskId, { status: "in_progress" });

  try {
    // 1. 检查 GITHUB_TOKEN
    if (!process.env.GITHUB_TOKEN) {
      throw new Error("GITHUB_TOKEN 环境变量未设置，无法创建 PR");
    }

    // 2. 解析仓库信息
    var repoInfo = parseRepo();
    var baseBranch = process.env.GITHUB_BASE_BRANCH || "develop";

    // 3. 生成分支名
    var slug = generateBranchSlug(cleanContent);
    var branchName = "codex/" + slug + "-" + Date.now();

    // 4. 创建分支
    var branchResult = await createBranch(
      repoInfo.owner, repoInfo.repo, branchName, baseBranch
    );

    // 5. 生成并提交 plan 文件
    var planContent = generatePlanContent(cleanContent);
    var filePath = "plans/codex-" + Date.now() + ".md";
    await commitFile(
      repoInfo.owner, repoInfo.repo, branchName,
      filePath,
      planContent,
      "codex: plan for " + sanitizeOutput(cleanContent).slice(0, 60)
    );

    // 6. 创建 Draft PR
    var prTitle = "codex: " + sanitizeOutput(cleanContent).slice(0, 80);
    var prBody = generatePRBody(cleanContent, branchName, taskId);
    var pr = await createDraftPR(
      repoInfo.owner, repoInfo.repo,
      prTitle, branchName, baseBranch, prBody
    );

    // 7. 构建结果
    var prLines = [
      "[Codex PR Agent] Draft PR 已创建",
      "",
      "任务: " + sanitizeOutput(cleanContent),
      "分支: " + branchName,
      "PR: " + pr.html_url,
      "状态: Draft (需手动 Review 后合并)",
      "",
      "文件: " + filePath
    ];

    var result = {
      task_id: taskId,
      agent: "codex",
      plan: prLines.join("\n"),
      estimated_time: "已完成",
      mode: "create-pr",
      pr_url: pr.html_url,
      pr_number: pr.number,
      branch: branchName,
      file: filePath,
      security_warnings: security.warnings,
      timestamp: new Date().toISOString()
    };

    updateTask(taskId, {
      status: "completed",
      result: JSON.stringify(result)
    });

    return {
      success: true,
      task_id: taskId,
      result: result
    };

  } catch (err) {
    var errorMsg = err.message || String(err);

    var failResult = {
      task_id: taskId,
      agent: "codex",
      error: errorMsg,
      mode: "create-pr",
      timestamp: new Date().toISOString()
    };

    updateTask(taskId, {
      status: "failed",
      result: JSON.stringify(failResult)
    });

    return {
      success: false,
      task_id: taskId,
      error: "PR 创建失败: " + errorMsg,
      result: failResult
    };
  }
}

module.exports = {
  execute: execute,
  isCreatePRRequest: isCreatePRRequest,
  stripConfirmKeyword: stripConfirmKeyword,
  generateBranchSlug: generateBranchSlug,
  generatePlanContent: generatePlanContent,
  generatePRBody: generatePRBody,
  mockPlanOnly: mockPlanOnly
};
